openapi: 3.1.0
info:
  version: 1.0.0
  title: WaterWise App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of WaterWise App
tags:
  - name: Water
    description: Operations with water consumption.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://api.contacts-backend.kesug.com
  - url: https://nodejs-hw-mongodb-ebwt.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/request-reset-password:
    post:
      $ref: '../swagger/paths/auth/requestResetPassword.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/resetPwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
