openapi: 3.1.0
info:
  version: 1.0.0
  title: WaterWise App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of WaterWise App
tags:
  - name: Water
    description: Operations with water consumption.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://waterwise-backend.onrender.com
paths:
  /v1/auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /v1/auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /v1/auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /v1/auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /v1/auth/request-reset-password:
    post:
      $ref: '../swagger/paths/auth/requestResetPassword.yaml'
  /v1/auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/resetPwd.yaml'
  /v1/auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/googleUrl.yaml'
  /v1/auth/confirm-oauth:
    post:
      $ref: '../swagger/paths/auth/loginWithGoogle.yaml'
  /v1/water:
    post:
      $ref: '../swagger/paths/water/post.yaml'
  /v1/water/daily:
    get:
      $ref: '../swagger/paths/water/getDaily.yaml'
  /v1/water/monthly:
    get:
      $ref: '../swagger/paths/water/getMonthly.yaml'
  /v1/water/{id}:
    patch:
      $ref: '../swagger/paths/water/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
